#!/bin/bash
# nginx_get_src --- Script for downloading a Nginx source tarball and
# verifying its GPG signature.

# Copyright (C) 2011 António P. P. Almeida <appa@perusio.net>

# Author: António P. P. Almeida <appa@perusio.net>

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written authorization.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

###  Script that downloads the nginx source, checks the signature,
###  renames according to debian convention and extracts the tarball

SCRIPTNAME=${0##*/}

WGET=$(which wget)
[ -x $WGET ] || exit 0

## Check the args.
if [ $# -ne 1 ]; then
    echo "Usage: $SCRIPTNAME <nginx-version>."
    exit 1
fi

## The nginx source URI.
NGINX_SRC=nginx-$1.tar.gz
NGINX_SRC_URL="http://nginx.org/download/$NGINX_SRC"

## Create a temporary directory and get the nginx source on it.
TEMPDIR=$(mktemp -d)
$WGET -P $TEMPDIR $NGINX_SRC_URL

## Get the signature.
NGINX_SRC_SIG="nginx-$1.tar.gz.asc"
NGINX_SRC_URL_SIG="http://nginx.org/download/$NGINX_SRC_SIG"
$WGET -P $TEMPDIR $NGINX_SRC_URL_SIG

## Verify the signature.
GPG=$(which gpg)
[ -x $GPG ] || exit 0

$GPG --verify $TEMPDIR/$NGINX_SRC_SIG || exit 1

## Rename the tarball and extract it.
NGINX_PKG_SRC_DIR=$HOME/C/nginx
NGINX_PKG_SRC_FILENAME=$NGINX_PKG_SRC_DIR/nginx_$1.orig.tar.gz
[ -d $NGINX_PKG_SRC_DIR ] || exit 0

mv $TEMPDIR/$NGINX_SRC $NGINX_PKG_SRC_FILENAME

CURRENT_DIR=$(pwd)
cd $NGINX_PKG_SRC_DIR && tar zxvf $NGINX_PKG_SRC_FILENAME

## Remove the temp dir.
rm -fr $TEMPDIR

## Go back to the original directory.
cd $CURRENT_DIR
